[package]
name = "abes_nice_things"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
serde = { version = "1", features = ["derive"]}
toml = "0.5"
dirs = "3.0"
sequential-test = "0.2.4"
rand = "0.8"

[features]
default = []
file_ops = []
ai = []