[package]
name = "abes_nice_things"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abes_nice_procs = { git = "https://github.com/Course-Brains/abes_nice_procs.git", rev = "445599f" }

[dev-dependencies]

[features]
default = []
dyn_binary = []
transmute_binary = []
